name: flutter_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
   

  english_words: ^4.0.0
  provider: ^6.1.2
  lottie: ^2.2.0
  http: ^1.3.0
  get:
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.3
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.3
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  image_picker: ^1.1.2
  path: ^1.9.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" 
  min_sdk_android: 21




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/